import { T } from '@/components/locale';
import { pageSeo } from '@/content/locales/seo';
import type { Metadata } from 'next';
import { PageHeading } from '@/components/layout';
import { profile, skills, tools } from '@/content/profile';
import { experience } from '@/content/experience';
import { asset } from '@/lib/site';
export const metadata: Metadata = { title: { absolute: pageSeo('/cv').title }, description: pageSeo('/cv').description, openGraph: { ...pageSeo('/cv'), locale: 'vi_VN' }, twitter: { ...pageSeo('/cv') } };
export default function CV() { return <section className="section cv-page"><PageHeading label="EXPERIENCE / EDUCATION / PRACTICE" title="Lê Triệu Phi" text={profile.title} /><div className="cv-downloads">{(['vi', 'en'] as const).map(lang => profile.cv[lang] ? <a key={lang} className="pill-link" href={asset(profile.cv[lang])} download><T>{lang === 'vi' ? 'Download CV — Vietnamese' : 'Download CV — English'}</T> ↓</a> : <button key={lang} className="pill-link" disabled><T>{lang === 'vi' ? 'Download CV — Vietnamese' : 'Download CV — English'}</T> <span><T>{"Coming soon"}</T></span></button>)}</div><div className="cv-layout"><aside><section><h2><T>{"Education"}</T></h2><p><T>{"Van Lang University"}</T><br /><T>{"Digital Art & Design"}</T></p><span><T>{"Third-year student · K30"}</T></span></section><section><h2><T>{"Languages"}</T></h2><p><T>{"Vietnamese — Native"}</T><br /><T>{"English — VSTEP B2"}</T></p></section><section><h2><T>{"Contact"}</T></h2><a href={`mailto:${profile.email}`}>{profile.email}</a></section></aside><div><h2 className="cv-section-title"><T>{"Experience"}</T></h2>{experience.map(e => <section className="cv-experience" key={e.company}><span className="eyebrow"><T>{e.dates}</T></span><h3><T>{e.role}</T></h3><h4><T>{e.company}</T></h4><p><T>{e.detail}</T></p></section>)}<h2 className="cv-section-title"><T>{"Skills"}</T></h2><p className="skill-list"><T>{skills.join(' · ')}</T></p><h2 className="cv-section-title"><T>{"Tools"}</T></h2><div className="tool-grid">{Object.entries(tools).map(([group, list]) => <div key={group}><h3><T>{group}</T></h3><p><T>{list.join(' / ')}</T></p></div>)}</div></div></div></section>; }
